import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { useLocalStorage } from "../hooks";

const dayInMiliseconds = 86400000;

const Home: NextPage = () => {
  const [year, setYear] = useLocalStorage<string>("year", "");
  const [hasReset, setHasReset] = useState(false);

  const daysLeft = Math.round(
    new Date(`January 1, ${year}`).getTime() / dayInMiliseconds -
      new Date().getTime() / dayInMiliseconds
  );

  return (
    <>
      <Head>
        <title>Days Till Death</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full bg-zinc-900 flex flex-col items-center justify-center min-h-screen p-4">
        {hasReset && (
          <div className="flex items-center">
            <input
              type="text"
              id="first_name"
              className="mr-2 w-48 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Year"
              required
              value={year}
              onChange={(e) => setYear(e.target.value)}
            />
            <button
              className="mt-2 text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
              onClick={() => {
                setHasReset(false);
              }}
            >
              Save
            </button>
          </div>
        )}
        {!hasReset && (
          <>
            <p className="text-6xl text-transparent bg-clip-text bg-gradient-to-br from-purple-600 to-blue-500 ">
              {daysLeft}
            </p>
            <p className="text-6xl text-transparent bg-clip-text bg-gradient-to-br from-purple-600 to-blue-500 ">
              Days Until Death
            </p>
          </>
        )}
        <div className="fixed bottom-0 mb-2">
          <button
            className="mt-2 text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
            onClick={() => {
              setHasReset(true);
            }}
          >
            Reset
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
